"""added photo file to users table

Revision ID: 04e3c0bf395f
Revises: 27926e72d885
Create Date: 2023-01-18 08:44:18.231361+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e3c0bf395f'
down_revision = '27926e72d885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('photo_file_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'profile', 'file_object', ['photo_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'photo_file_id')
    # ### end Alembic commands ###
