"""added geo_locations table

Revision ID: 05a0e5bd80dd
Revises: d1eae6045afc
Create Date: 2022-12-07 00:58:24.581048+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a0e5bd80dd'
down_revision = 'd1eae6045afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
