"""create main roles table

Revision ID: 06eb97ed35b6
Revises: 11efc3732b22
Create Date: 2022-11-22 08:43:43.835866+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eb97ed35b6'
down_revision = '11efc3732b22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
