"""create roles table

Revision ID: 11efc3732b22
Revises: c24021e3f773
Create Date: 2022-11-22 08:43:24.416489+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11efc3732b22'
down_revision = 'c24021e3f773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
