"""set profile photo file to SET NULL on delete

Revision ID: 1b85ba1e4496
Revises: c656408bc44a
Create Date: 2023-02-05 14:41:17.914508+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b85ba1e4496'
down_revision = 'c656408bc44a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_photo_file_id_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'file_object', ['photo_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key('profile_photo_file_id_fkey', 'profile', 'file_object', ['photo_file_id'], ['id'])
    # ### end Alembic commands ###
