"""added file objects and buckets to table

Revision ID: 27926e72d885
Revises: d1eae6045afc
Create Date: 2023-01-18 08:38:41.731524+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27926e72d885'
down_revision = 'd1eae6045afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucket_id'), 'bucket', ['id'], unique=False)
    op.create_table('file_object',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('bucket_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['bucket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_object_id'), 'file_object', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_object_id'), table_name='file_object')
    op.drop_table('file_object')
    op.drop_index(op.f('ix_bucket_id'), table_name='bucket')
    op.drop_table('bucket')
    # ### end Alembic commands ###
