"""remove constrains from title and created by, and made title unique in roles table

Revision ID: 3a25c4a34af5
Revises: f48d9fd879a3
Create Date: 2022-12-04 17:42:16.548611+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a25c4a34af5'
down_revision = 'f48d9fd879a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('title_created_by', 'roles', type_='unique')
    op.drop_index('ix_roles_title', table_name='roles')
    op.create_index(op.f('ix_roles_title'), 'roles', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_title'), table_name='roles')
    op.create_index('ix_roles_title', 'roles', ['title'], unique=False)
    op.create_unique_constraint('title_created_by', 'roles', ['title', 'created_by'])
    # ### end Alembic commands ###
