"""added index to title column in roles

Revision ID: 3c54d2416a3d
Revises: bc1885ee38bb
Create Date: 2022-12-01 05:27:02.627005+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c54d2416a3d'
down_revision = 'bc1885ee38bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_title'), 'roles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_title'), table_name='roles')
    # ### end Alembic commands ###
