"""added total bytes to file object

Revision ID: 8634157233f5
Revises: 96851bb75883
Create Date: 2023-01-18 11:00:22.722165+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8634157233f5'
down_revision = '96851bb75883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'total_bytes')
    op.add_column('file_object', sa.Column('total_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_object', 'total_bytes')
    op.add_column('bucket', sa.Column('total_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
