"""added last_password_token to users table

Revision ID: 8c67e47f9d8d
Revises: 958ebe53e9ce
Create Date: 2022-11-26 05:48:14.018001+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c67e47f9d8d'
down_revision = '958ebe53e9ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_password_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_token')
    # ### end Alembic commands ###
