"""changed other_names to first_name in profile table

Revision ID: 958ebe53e9ce
Revises: 06eb97ed35b6
Create Date: 2022-11-23 06:58:44.113063+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958ebe53e9ce'
down_revision = '06eb97ed35b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.drop_column('profile', 'other_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('other_names', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('profile', 'first_name')
    # ### end Alembic commands ###
