"""added total bytes to bucket table

Revision ID: 96851bb75883
Revises: 04e3c0bf395f
Create Date: 2023-01-18 09:42:25.218021+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96851bb75883'
down_revision = '04e3c0bf395f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('total_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'total_bytes')
    # ### end Alembic commands ###
