"""added unique constraint between title and created by

Revision ID: bc1885ee38bb
Revises: 4e2987ca8ec3
Create Date: 2022-12-01 05:22:43.770131+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1885ee38bb'
down_revision = '4e2987ca8ec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('title_created_by', 'roles', ['title', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('title_created_by', 'roles', type_='unique')
    # ### end Alembic commands ###
