"""added mime_type and extension to file object table

Revision ID: c656408bc44a
Revises: 860b3d312ef0
Create Date: 2023-01-28 15:54:25.752791+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c656408bc44a'
down_revision = '860b3d312ef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_object', sa.Column('extension', sa.String(length=100), nullable=True))
    op.add_column('file_object', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_object', 'mime_type')
    op.drop_column('file_object', 'extension')
    # ### end Alembic commands ###
