"""added unqiue constraints between user_id and role_id in user_roles table

Revision ID: f48d9fd879a3
Revises: 3c54d2416a3d
Create Date: 2022-12-01 05:57:16.676533+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48d9fd879a3'
down_revision = '3c54d2416a3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_id_and_role_id_unique_constraint', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_and_role_id_unique_constraint', 'user_roles', type_='unique')
    # ### end Alembic commands ###
